### ISSUE TITLE
storageType naming

### ISSUE THREAD

**Issue by AFoletti** [blw-ofag-ufag/eCH-0262#3]
https://github.com/blw-ofag-ufag/eCH-0262/blob/3972efe9df7497f8545fea57c882d15534b52afa/src/eCH-0262-1-0.xsd#L78C22-L78C33

The "storageType" complexType has an element named "storageType".
My proposal is to change the element name to simple "type" to avoid confusion

**Comment by lars-steffen** [comment]
changed to "storageKind" in #9
