### ISSUE TITLE
verify cardinality of applicationTechnologyType:id

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0262#6]
Id is currently assigned a cardinality of 1-2.

If this list is static, then 1 would seem to be enough.

If not, we should introduce alternateId with a cardinaltiy of 1.

**Comment by anjaaeschlimann** [comment]
Denke AlternateID macht sinn. dann auch ok für allfällige Weiterentwicklung der Liste / FMIS die eigene ID haben
